export const REQUIRED_ENV_KEYS = [
  'DATABASE_URL',
  'JWT_ACCESS_SECRET',
  'JWT_REFRESH_SECRET',
  'REFRESH_TOKEN_HASH_SECRET',
  'COOKIE_SECRET',
  'GOOGLE_CLIENT_ID',
  'GOOGLE_CLIENT_SECRET',
] as const;

export const OPTIONAL_NUMBER_ENV_KEYS = [
  'PORT',
  'AUTH_LOGIN_MAX_ATTEMPTS',
  'AUTH_EMAIL_MAX_FAILED_ATTEMPTS',
  'AUTH_LOCK_WINDOW_MINUTES',
  'AUTH_EMAIL_LOCK_SECONDS',
  'AUTH_IP_MAX_ATTEMPTS',
  'AUTH_IP_MAX_FAILED_ATTEMPTS',
  'AUTH_IP_LOCK_SECONDS',
  'AUTH_ATTEMPT_WINDOW_SECONDS',
  'AUTH_LOGIN_TTL_SECONDS',
  'AUTH_LOGIN_LIMIT',
  'AUTH_LOGIN_THROTTLE_TTL_SECONDS',
  'AUTH_LOGIN_THROTTLE_LIMIT',
  'AUTH_REGISTER_TTL_SECONDS',
  'AUTH_REGISTER_LIMIT',
  'AUTH_REFRESH_TTL_SECONDS',
  'AUTH_REFRESH_LIMIT',
  'AUTH_CSRF_TTL_SECONDS',
  'AUTH_CSRF_LIMIT',
] as const;

export const OPTIONAL_BOOLEAN_ENV_KEYS = ['TURNSTILE_ENABLED'] as const;
